### ISSUE TITLE
KeycloakRealm reconciliation not triggered at control loop interval frequency

### ISSUE THREAD

**Issue by y3lousso** [DoodleScheduling/keycloak-controller#200]
#### Describe the bug
KeycloakRealm CR does not reconcile in a loop

#### To Reproduce
Set the spec.interval to 15s, check the KeycloakRealm Events

```
apiVersion: keycloak.infra.doodle.com/v1beta1
kind: KeycloakRealm
metadata:
  name: master
  namespace: keycloak
spec:
  interval: 15s
  ...
```

Check the KeycloakRealm Events
![image](https://github.com/DoodleScheduling/keycloak-controller/assets/23299699/9bba0867-fe4f-4e68-8937-e542d63da630)

I do not have the Suspended property set.
Basically, the loop stops. If I change some config via the UI, it never gets overriden.

#### Expected behavior
At interval=15, I would expect 4 reconciliation events per minutes, in this screenshot 4min44 ~ 18 events, but we only get 2.

#### Environment
 - controller version: 2.2.0
 - keycloak version: 24.0.1
 - kubernetes version: 1.27.7
