### ISSUE TITLE
KeycloakClient Roles

### ISSUE THREAD

**Issue by eXist-FraGGer** [DoodleScheduling/keycloak-controller#403]
#### Is your feature request related to a problem? Please describe
I need to create a client with roles.

#### Describe the solution you'd like
It can be
```yaml
apiVersion: keycloak.infra.doodle.com/v1beta1
kind: KeycloakClient
metadata:
  name: kc-client-example
spec:
  client:
    clientId: shortcut
    name: Shortcut
    description: Client for shortcut
    clientAuthenticatorType: client-secret
    secret: "123123123123"
    enabled: true
    redirectUris:
    - https://frontend/
    attributes:
      "oauth2.device.authorization.grant.enabled": "true"
    webOrigins:
      - +
    roles:
      - name: management
        description: Some role
```

#### Additional context

So this should create a role here:

<img width="1283" alt="Image" src="https://github.com/user-attachments/assets/3cd392e8-2b3d-4ec8-9ce8-1dc77d180768" />
